version: "3.5"

services:

  frontend:  
    build: ./frontend
    restart: always
    stdin_open: true
    container_name: stuff_frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_SERVER_LINK=${REACT_APP_SERVER_LINK}
      - REACT_APP_TMDB_IMG_LINK=${REACT_APP_TMDB_IMG_LINK}
      - PORT=${FRONTEND_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - stuff_network

  server:
    build: ./server
    restart: always
    container_name: stuff_server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - SERVER_PORT=${SERVER_PORT}
      - FRONTEND_LINK=${FRONTEND_LINK}
      - GTA_SERVER_LINK=${GTA_SERVER_LINK}
      - GTA_AUTH=${GTA_AUTH}
      - NODE_ENV=${SERVER_STATUS}
      - SECRET=${SECRET}
      - PGHOST=${DB_CONTAINER_NAME}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPORT=5432
      - PGPASS=${PGPASS}
      - TMDB_LINK=${TMDB_LINK}
      - TMDB_IMG_LINK=${TMDB_IMG_LINK}
      - IGDB_CLIENT=${IGDB_CLIENT}
      - IGDB_SECRET=${IGDB_SECRET}
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
      - gta_server
    networks:
      - stuff_network

  db:
    image: postgres:15
    restart: always
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - ${PGPORT}:5432
    user: ${PGUSER}
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASS}
      - POSTGRES_DB=${PGDATABASE}
    volumes:
      - ./db/user_table.sql:/docker-entrypoint-initdb.d/01_user.sql
      - ./db/user_movie_table.sql:/docker-entrypoint-initdb.d/02_movie.sql
      - ./db/movie_table.sql:/docker-entrypoint-initdb.d/03_movie_table.sql
      - ./db/todo_table.sql:/docker-entrypoint-initdb.d/04_todo.sql
      - ./db/books_table.sql:/docker-entrypoint-initdb.d/05_book.sql
      - ./db/c_console.sql:/docker-entrypoint-initdb.d/06_game.sql
    networks:
      - stuff_network

  gta_server:
    build: ./gta_server
    restart: always
    container_name: ${GTA_CONTAINER_NAME}
    ports:
      - ${GTA_SERVER_PORT}:${GTA_SERVER_PORT}
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - SECRET=${SECRET}
      - SERVER_PORT=${GTA_SERVER_PORT}
      - GTA_CONNECTION_STRING=${GTA_CONNECTION_STRING}
      - GTA_AUTH=${GTA_AUTH}
    volumes:
      - ./gta_server:/app
      - /app/node_modules
    networks:
      - stuff_network
      
networks:
  stuff_network:
    name: stuff_network
    